export const resources = {
  BUTTON: {
    BUTTON_PLACEHOLDER_ADD: "Add new",
    BUTTON_PLACEHOLDER_SEARCH: "Search",
    BUTTON_PLACEHOLDER_EDIT: "Edit",
    BUTTON_PLACEHOLDER_DELETE: "Delete",
    BUTTON_PLACEHOLDER_SHOW: "Show all",
    BUTTON_PLACEHOLDER_REFRESH: "Refresh",
    BUTTON_PLACEHOLDER_UPDATE: "Update",
    BUTTON_PLACEHOLDER_CANCEL: "Cancel",
    BUTTON_PLACEHOLDER_SUBMIT: "Submit",
  },
  TITLES: {
    TITLES_PLACEHOLDER_HEADER: "Services",
    TITLES_PLACEHOLDER_ADD: "Add new service",
    TITLES_PLACEHOLDER_EDIT: "Edit service",
  },

  SERVICES: {
    SERVICE_PLACEHOLDER_TITLE: "Project:",
    SERVICE_PLACEHOLDER_ID: "id:",
    SERVICE_PLACEHOLDER_SERVICE: "Service:",
    SERVICE_PLACEHOLDER_CUSTOMER: "Customer:",
    SERVICE_PLACEHOLDER_COUNTRY: "Country:",
    SERVICE_PLACEHOLDER_CITY: "City:",
    SERVICE_PLACEHOLDER_STATUS: "Status:",
    SERVICE_PLACEHOLDER_START: "Start:",
    SERVICE_PLACEHOLDER_DONE: "Done:",
  },

  INPUT: {
    INPUT_PLACEHOLDER_ENTERID: "Enter Service Id",
  },

  FORMDATA: {
    FORMDATA_PLACEHOLDER_TYPE_PAVEMENT: "Pavement",
    FORMDATA_PLACEHOLDER_TYPE_CONCRETE: "Concrete",
    FORMDATA_PLACEHOLDER_TYPE_FOUNDATIONING: "Foundationing",
    FORMDATA_PLACEHOLDER_TYPE_INFRA_SERVICE: "Infra Service",

    FORMDATA_PLACEHOLDER_COUNTRIES_SWEDEN: "Sweden",
    FORMDATA_PLACEHOLDER_COUNTRIES_DENMARK: "Denmark",
    FORMDATA_PLACEHOLDER_COUNTRIES_NORWAY: "Norway",

    FORMDATA_PLACEHOLDER_CITIES_STOCKHOLM: "Stockholm",
    FORMDATA_PLACEHOLDER_CITIES_COPENHAGEN: "Copenhagen",
    FORMDATA_PLACEHOLDER_CITIES_OSLO: "Oslo",

    FORMDATA_PLACEHOLDER_STATUS_ONGOING: "Ongoing",
    FORMDATA_PLACEHOLDER_STATUS_NOTSTARTED: "Not started",

    FORMDATA_PLACEHOLDER_LABELS_PROJECT_TITLE: "Project Name",
    FORMDATA_PLACEHOLDER_LABELS_PROJECT_TYPE: "Select type of service",
    FORMDATA_PLACEHOLDER_LABELS_PROJECT_START: "Start",
    FORMDATA_PLACEHOLDER_LABELS_PROJECT_END: "End",
    FORMDATA_PLACEHOLDER_LABELS_PROJECT_CUSTOMER: "Customer",
    FORMDATA_PLACEHOLDER_LABELS_PROJECT_COUNTRY: "Select Country",
    FORMDATA_PLACEHOLDER_LABELS_PROJECT_CITY: "Select City",
    FORMDATA_PLACEHOLDER_LABELS_PROJECT_STATUS: "Project Status",
    FORMDATA_PLACEHOLDER_LABELS_PROJECT_BUTTON: "Update",
  },

  SWALDATA: {
    SWALDATA_DELETE_QUESTION_TITLE: "Are you sure?",
    SWALDATA_DELETE_QUESTION_TEXT: "You won't be able to revert this!",
    SWALDATA_DELETE_CONFIRM_BUTTON: "Yes, delete it!",
    SWALDATA_DELETE_CANCEL_BUTTON: "No, cancel!",
    SWALDATA_DELETE_SUCESS: "Service deleted!",
    SWALDATA_DELETE_SUCESS_SPAN: "Redirecting to homepage...",

    SWALDATA_EDIT_SUCESS: "Service edited!",
    SWALDATA_EDIT_SUCESS_SPAN: "Redirecting to homepage...",
  },
};
